export const FETCH_HOSTNAMES = 'FETCH_HOSTNAMES';
// export const FETCH_HOSTNAMES_BEGIN= 'FETCH_HOSTNAMES_BEGIN';
export const FETCH_APPZ = 'FETCH_APPZ';
export const FETCH_COMPT_APPZ = 'FETCH_COMPT_APPZ';
